#!/bin/bash -ex

virtualenv -p python3 clusternomics
. clusternomics/bin/activate
CPUWHEEL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0rc2-cp35-cp35m-linux_x86_64.whl
GPUWHEEL=https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-1.0.0rc2-cp35-cp35m-linux_x86_64.whl
pip3 install --upgrade $CPUWHEEL
pip3 install -r reqd-pkgs.txt
pip3 install --upgrade neovim
